export const styles = {
  publicNav: {
    position: 'fixed', top: 0, left: 0, right: 0, height: '60px',
    backgroundColor: 'rgba(0, 0, 0, 0.45)', backdropFilter: 'blur(8px)',
    display: 'flex', justifyContent: 'space-between', alignItems: 'center',
    padding: '0 25px', zIndex: 100,
  },
  publicNavBtn: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)', color: '#ffffff',
    border: '1px solid rgba(255, 255, 255, 0.4)', padding: '8px 14px',
    borderRadius: '6px', cursor: 'pointer', fontSize: '13px', fontWeight: 'bold',
  },
  largeModalCard: {
    backgroundColor: '#ffffff', padding: '25px', borderRadius: '12px',
    width: '550px', maxWidth: '90%', maxHeight: '80vh', overflowY: 'auto',
    boxShadow: '0 8px 32px rgba(0,0,0,0.3)',
  },
  closeBtn: { background: 'none', border: 'none', fontSize: '18px', cursor: 'pointer', color: '#888', fontWeight: 'bold' },
  loginWrapper: {
    minHeight: '100vh', width: '100vw', position: 'fixed', top: 0, left: 0,
    backgroundImage: `linear-gradient(rgba(0, 0, 0, 0.65), rgba(0, 0, 0, 0.65)), url("https://www.ukm.my/kelestarian/wp-content/uploads/green-spaces/dectar-edit-scaled-1-1024x680.jpeg")`,
    backgroundSize: 'cover', backgroundPosition: 'center', backgroundRepeat: 'no-repeat',
    display: 'flex', justifyContent: 'center', alignItems: 'center', padding: '70px 20px 20px 20px', boxSizing: 'border-box',
  },
  loginCard: {
    backgroundColor: '#ffffff', padding: '30px 25px', borderRadius: '12px',
    boxShadow: '0 8px 24px rgba(0,0,0,0.3)', maxWidth: '440px', width: '100%', maxHeight: '82vh', overflowY: 'auto',
  },
  container: { fontFamily: 'Arial, sans-serif', maxWidth: '1150px', margin: '20px auto', padding: '0 15px' },
  headerBar: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#ffffff', padding: '15px 20px', borderRadius: '8px', boxShadow: '0 2px 8px rgba(0,0,0,0.1)', marginBottom: '20px' },
  profileLeftGroup: { display: 'flex', alignItems: 'center', gap: '12px' },
  avatarIcon: { fontSize: '28px', backgroundColor: '#e9ecef', width: '45px', height: '45px', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  profileName: { fontSize: '16px', fontWeight: 'bold', color: '#212529' },
  profileSubtext: { fontSize: '12px', color: '#6c757d', marginTop: '2px' },
  roleBadge: { backgroundColor: '#0056b3', color: '#fff', padding: '2px 6px', borderRadius: '4px', fontSize: '11px', fontWeight: 'bold' },
  card: { backgroundColor: '#ffffff', padding: '20px', borderRadius: '8px', boxShadow: '0 2px 8px rgba(0,0,0,0.1)' },
  portalGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' },
  portalCard: { backgroundColor: '#fff', borderLeft: '6px solid', padding: '25px', borderRadius: '8px', boxShadow: '0 4px 12px rgba(0,0,0,0.08)', cursor: 'pointer', transition: 'transform 0.2s' },
  portalIcon: { fontSize: '36px', marginBottom: '10px' },
  portalTitle: { margin: '0 0 10px 0', fontSize: '18px' },
  portalDesc: { fontSize: '13px', color: '#666', lineHeight: '1.4', marginBottom: '15px' },
  accessBadge: { display: 'inline-block', color: '#fff', padding: '4px 10px', borderRadius: '20px', fontSize: '12px', fontWeight: 'bold' },
  pageTitleBar: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '15px' },
  backButton: { backgroundColor: '#6c757d', color: '#fff', border: 'none', padding: '8px 14px', borderRadius: '4px', cursor: 'pointer', fontWeight: 'bold' },
  form: { display: 'flex', flexDirection: 'column', gap: '12px' },
  gridTwo: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' },
  gridThree: { display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '10px' },
  gridFour: { display: 'grid', gridTemplateColumns: '1fr 1fr 1fr 1fr', gap: '10px' },
  label: { fontSize: '13px', fontWeight: 'bold', marginBottom: '4px', display: 'block' },
  input: { padding: '10px', fontSize: '14px', borderRadius: '4px', border: '1px solid #ccc', width: '100%', boxSizing: 'border-box' },
  button: { padding: '10px 16px', fontSize: '14px', backgroundColor: '#0056b3', color: '#ffffff', border: 'none', borderRadius: '4px', cursor: 'pointer', fontWeight: 'bold' },
  smallButton: { padding: '5px 8px', fontSize: '12px', backgroundColor: '#0056b3', color: '#ffffff', border: 'none', borderRadius: '4px', cursor: 'pointer', fontWeight: 'bold' },
  link: { color: '#0056b3', cursor: 'pointer', textDecoration: 'underline' },
  table: { width: '100%', borderCollapse: 'collapse', marginTop: '10px', textAlign: 'left', fontSize: '13px' },
  th: { padding: '10px', borderBottom: '2px solid #dee2e6' },
  td: { padding: '10px' },
  statCard: { backgroundColor: '#ffffff', padding: '15px', borderRadius: '8px', boxShadow: '0 2px 6px rgba(0,0,0,0.08)', textAlign: 'center' },
  statNumber: { fontSize: '26px', fontWeight: 'bold', color: '#0056b3' },
  statLabel: { fontSize: '12px', color: '#666', marginTop: '4px' },
  modalOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.6)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1000 },
  modalCard: { backgroundColor: '#fff', padding: '25px', borderRadius: '8px', width: '380px', boxShadow: '0 4px 16px rgba(0,0,0,0.2)' }
};